name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - name: Install gocode
      run: go install github.com/mdempsky/gocode@latest
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Lint
      run: make lint
